### ISSUE TITLE
Appreciation (Faculty-Staff)

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/hubbabubba-chewbacca-migration#21]
# Form Migration

## Old Form Information

- **Form URL:** https://forms.mercer.edu/appreciation/
- **Handler URL:** https://apps.mercer.edu/forms/appreciation.cfm
- **To:** _none_
- **From:** _none_
- **Subject:** _none_
- **Redirect:** https://forms.mercer.edu/appreciation/thanks.shtm

## New Form information

```html
<form ... action="https://formhandlers.mercer.edu/" ... >
```

Remove unused fields below.

(But nothing will break if it's blank.)

```html
<!-- Testing -->
<input type="hidden" name="*debug" value="false">
<!-- Required -->
<input type="hidden" name="*to" value="webmaster@mercer.edu">
<!-- Recommended -->
<input type="hidden" name="*formname" value="Faculty–Staff Appreciation Day">
<input type="hidden" name="*redirect" value="https://forms.mercer.edu/appreciation/thanks.shtm">
<input type="hidden" name="*subject" value="Faculty–Staff Appreciation Day">
<!-- Situational -->
<input type="hidden" name="*bcc" value="">
<input type="hidden" name="*cc" value="">
<input type="hidden" name="*honeypot" value="">
<input type="hidden" name="*replyto" value="">
```

## Tasks

- [ ] Update form action attribute
- [ ] Add hidden fields
- [ ] Verify action and hidden field values are correct
- [ ] Test

**Comment by Sporkyy** [comment]
- This occurs once a year.
- The form submits to something that records it in a database.
- This should be possible to handle with the formhandlers site, but the output component will need to be finished first.

I'll go ahead and be optimistic and migrate it without the output component.

**Comment by Sporkyy** [comment]
This is apparently in the CMS now.

http://hr.mercer.edu/appreciation/

I'm not doing anything else now, but the site on forms.mercer.edu/appreciation should be removed at some point.
