### ISSUE TITLE
Theology Event Registration

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/hubbabubba-chewbacca-migration#33]
# Form Migration

## Old Form Information

- **Form URL:** http://theology.mercer.edu/forms/events.cfm
- **customcf Include:** /www/mu-theology/forms/customcf/events_registration.cfm
- **Handler URL:** https://apps.mercer.edu/forms/theology_events_registration.cfm
- **To:** frazier_d@mercer.edu
- **From:** _from form_
- **Subject:** Event Registration
- **Redirect:** http://theology.mercer.edu/forms/events.cfm

## New Form information

```html
<form ... action="https://formhandlers.mercer.edu/" ... >
```

Remove unused fields below.

(But nothing will break if it's blank.)

```html
<!-- Testing -->
<input type="hidden" name="*debug" value="">
<!-- Required -->
<input type="hidden" name="*to" value="frazier_d@mercer.edu">
<!-- Recommended -->
<input type="hidden" name="*formname" value="Theology - Event Registration">
<input type="hidden" name="*redirect" value="http://theology.mercer.edu/forms/events.cfm">
<input type="hidden" name="*subject" value="Event Registration">
<!-- Situational -->
<input type="hidden" name="*bcc" value="">
<input type="hidden" name="*cc" value="">
<input type="hidden" name="*honeypot" value="">
<input type="hidden" name="*replyto" value="">
```

## Tasks

- [x] Update form action attribute
- [x] Add hidden fields
- [x] Verify action and hidden field values are correct
- [x] Synchronize the ROPS
- [x] Test

**Comment by Sporkyy** [comment]
Added a "Synchronize ROPS" checkbox.
