### ISSUE TITLE
Formhandlers Migration

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/hubbabubba-chewbacca-migration#34]
[Formhandlers Repo](https://github.com/InteractiveDesignAndDevelopment/formhandlers)
(Which is based on [Formspree](https://github.com/formspree/formspree#1-setup-the-html-form))

[Spreadsheet](https://docs.google.com/spreadsheets/d/1o5C-VXC19Vd12N9DiYeTQiT8AUwPI-D14CALvzeeqHU/edit?ts=5a315252#gid=0)

**Comment by cinakur** [comment]
# Checklist (Example)

## Old Form Information

- Form URL:
- Handler URL:
- To:
- From:
- Subject:
- Redirect:

### New Form information

```html
<form ... action="https://formhandlers.mercer.edu/" ... >
```

Remove unused fields below.

(But nothing will break if it's blank.)

```html
<!-- Required -->
<input type="hidden" name="to" value="">
<!-- Recommended -->
<input type="hidden" name="formname" value="">
<input type="hidden" name="redirect" value="">
<input type="hidden" name="subject" value="">
<!-- Situational -->
<input type="hidden" name="bcc" value="">
<input type="hidden" name="cc" value="">
<input type="hidden" name="honeypot" value="">
<input type="hidden" name="replyto" value="">
```

### Tasks

- [ ] Record Old Form Information
- [ ] Enter New Form Information values
- [ ] Update form action attribute
- [ ] Add hidden fields to bottom of form
- [ ] Verify action and hidden field values are correct
- [ ] Test form

**Comment by Sporkyy** [comment]
All done with help from @elcopeland
